absoluteurl: http://stdio-ghana.github.io
baseurl: ''
markdown: kramdown
markdown_ext: md
activeClass: class="active"
highlighter: pygments
encoding: utf-8
navPages:
 - schedule
 - instructors
 - sessions
 - students
 - projects
 - misc
 - reports
exclude:
 - run.sh
 - INSTALL.md
 - README.md
collections:
  instructors:
    output: true
  students:
    output: true
